In [1]:
# Importa a biblioteca 'numpy' e apelida como 'np'
import numpy as np

# Importa a biblioteca 'pandas' e apelida como 'pd'
import pandas as pd

Video: Series

In [2]:
# Lista de strings
labels = ['a', 'b', 'c']

In [3]:
# Uma lista
minha_lista = [10, 20, 30]

# Um array do NumPy
arr = np.array([10, 20, 30])

# Um dicionário : mapeia chaves (keys) a valores (values)
d = {'a':10, 'b':20, 'c':30}

In [4]:
# Cria uma Series usando a lista como valores e 'labels' como índice
pd.Series(data=minha_lista, index = labels)

a    10
b    20
c    30
dtype: int64

In [5]:
# Armazena a Series criada na variável 'series'
series = pd.Series(data=minha_lista, index = labels)

In [6]:
# Acessa e retorna o valor associado ao índice 'b' dentro da Series
series['b']

np.int64(20)

In [7]:
# Cria uma Series usando um array do NumPy como fonte de dados e a lista de labels como índice
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [8]:
# Cria uma Series chamada 'ser1' onde os valores são números inteiros e os índices são nomes de países
ser1 = pd.Series([1, 2, 3, 4], index=['EUA', 'Alemanha', 'URSS', 'Japão'])

In [9]:
# Exibe 'ser1'
ser1

EUA         1
Alemanha    2
URSS        3
Japão       4
dtype: int64

In [10]:
# Cria uma segunda Series 'ser2' com alguns países diferentes e em uma ordem distinta
ser2 = pd.Series([1, 2, 3, 4], index=['Alemanha', 'EUA', 'Itália', 'Japão'])

In [11]:
# Exibe 'ser2'
ser2

Alemanha    1
EUA         2
Itália      3
Japão       4
dtype: int64

In [12]:
# Realiza a soma das duas Series, alinhando os valores pelos seus respectivos índices (nomes dos países)
ser1 + ser2

Alemanha    3.0
EUA         3.0
Itália      NaN
Japão       8.0
URSS        NaN
dtype: float64

Video: DataFrame - Criação e Fatiamento

In [13]:
# Define uma 'semente' para o gerador de números aleatórios, garantindo que os resultados sejam os mesmos toda vez que o código for executado
np.random.seed(101)

In [14]:
# Cria um DataFrame preenchido com números aleatórios (distribuição normal)
# com 5 linhas (A a E) e 4 colunas (W a Z)
df = pd.DataFrame(np.random.randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split())

In [15]:
# Exibe 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [16]:
# Seleciona e extrai a coluna 'W' do DataFrame, retornando-a como uma Series
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [17]:
# Verifica o tipo de objeto da coluna selecionada
type(df['W'])

pandas.Series

In [18]:
# Verifica o tipo de objeto da variável 'df'
type(df)

pandas.DataFrame

In [19]:
# Seleciona múltiplas colunas do DataFrame ao mesmo tempo, retornando um novo DataFrame
df[['W', 'Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [20]:
# Acessa a coluna 'W' utilizando a notação de atributo
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [21]:
# Cria uma nova coluna chamada 'new', onde cada valor é a soma dos elementos das colunas 'W' e 'X'
df['new'] = df['W'] + df['X']

In [22]:
# Exibe 'df'
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [23]:
# Tenta remover a coluna 'new', especificando que a busca deve ser feita nas colunas (axis=1)
df.drop('new', axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
# Exibe 'df'
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [25]:
# Remove a coluna 'new' permanentemente do DataFrame original, sem precisar reatribuir a variáve
df.drop('new', axis=1, inplace=True)

In [26]:
# Exibe 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [27]:
# Seleciona uma linha específica pelo seu índice usando o indexador .loc
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [28]:
# Seleciona um subconjunto do DataFrame: as linhas 'A' e 'B' cruzadas com as colunas 'X', 'Y' e 'Z'
df.loc[['A', 'B'], ['X', 'Y', 'Z']]

          X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965

In [29]:
# Seleciona as linhas da posição 1 até a 3 (o 4 é exclusivo) 
# e as colunas da posição 2 até o final
df.iloc[1:4, 2: ]

          Y         Z
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057

Video: DataFrame - Seleção condicional, set_index

In [30]:
# Exibe 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
# Cria uma tabela de valores verdadeiros (True) ou falsos (False)
# comparando cada elemento do DataFrame com o número 0
bool = df > 0

In [32]:
# Filtra o DataFrame original: mantém os valores onde é True e substitui por NaN onde é False
df[bool]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [33]:
# Retorna apenas as linhas do DataFrame onde o valor na coluna 'W' é maior que zero
df[df['W'] > 0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [34]:
# Filtra o DataFrame para obter apenas as linhas onde 'W' > 0 e,
# desse resultado, extrai apenas a coluna 'Y'
df[df['W'] > 0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [35]:
# Cria um boolean baseado na coluna 'W'
bool = df['W'] > 0

# Aplica o boolean para criar um novo DataFrame (df2) apenas com as linhas filtradas
df2 = df[bool]

# Seleciona a coluna 'Y' desse novo DataFrame filtrado
df2['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [36]:
# Filtra o DataFrame para retornar linhas onde a coluna 'W' é maior que zero 
# OU a coluna 'Y' é maior que 1
df[(df['W'] > 0) | (df['Y'] > 1)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
# Exibe 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [38]:
# Transforma o índice atual (as letras A, B, C...) em uma coluna comum 
# e redefine o índice do DataFrame para números inteiros (0, 1, 2...)
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [39]:
# Exibe 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
# Cria uma lista de strings separando a frase pelos espaços em branco
col = 'RS RJ SP AM SC'.split()

In [41]:
# Exibe 'col'
col

['RS', 'RJ', 'SP', 'AM', 'SC']

In [42]:
# Cria uma nova coluna chamada 'Estado' e a preenche com os valores da lista 'col'
df['Estado'] = col

In [43]:
# Exibe 'df'
df

          W         X         Y         Z Estado
A  2.706850  0.628133  0.907969  0.503826     RS
B  0.651118 -0.319318 -0.848077  0.605965     RJ
C -2.018168  0.740122  0.528813 -0.589001     SP
D  0.188695 -0.758872 -0.933237  0.955057     AM
E  0.190794  1.978757  2.605967  0.683509     SC

In [44]:
# Define a coluna 'Estado' como o novo índice (rótulo das linhas) do DataFrame
df.set_index('Estado')

               W         X         Y         Z
Estado
RS      2.706850  0.628133  0.907969  0.503826
RJ      0.651118 -0.319318 -0.848077  0.605965
SP     -2.018168  0.740122  0.528813 -0.589001
AM      0.188695 -0.758872 -0.933237  0.955057
SC      0.190794  1.978757  2.605967  0.683509

In [45]:
# Exibe 'df'
df

          W         X         Y         Z Estado
A  2.706850  0.628133  0.907969  0.503826     RS
B  0.651118 -0.319318 -0.848077  0.605965     RJ
C -2.018168  0.740122  0.528813 -0.589001     SP
D  0.188695 -0.758872 -0.933237  0.955057     AM
E  0.190794  1.978757  2.605967  0.683509     SC

Video: DataFrame - Índices Multiníveis

In [46]:
# Cria duas listas que servirão como níveis do índice
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]

# Une as listas em pares (tuplas): [('G1', 1), ('G1', 2)...]
hier_index = list(zip(outside, inside))

# Transforma essas tuplas em um objeto MultiIndex oficial do Pandas
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [47]:
# Exibe 'outside'
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [48]:
# Exibe 'inside'
inside

[1, 2, 3, 1, 2, 3]

In [49]:
# Combina as listas 'outside' e 'inside' em uma lista de tuplas
# Resultado: [('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)
hier_index = list(zip(outside, inside))

In [50]:
# Exibe 'hier_index'
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [51]:
# Converte a lista de tuplas em um objeto MultiIndex oficial do Pandas
# Isso permite que o DataFrame entenda a hierarquia entre os níveis 'G1/G2' e '1/2/3'
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [52]:
# Exibe 'hier_index'
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [53]:
# Cria um DataFrame de 6 linhas e 2 colunas com números aleatórios
# index=hier_index: Aplica os níveis G1/G2 e 1/2/3 como rótulos das linhas
# columns=['A', 'B']: Define os nomes das colunas
df = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns=['A', 'B'])

In [54]:
# Exibe 'df'
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [55]:
# Primeiro seleciona o nível externo 'G1' (retorna um DataFrame menor)
# E depois seleciona a linha '1' dentro desse grupo (retorna uma Series)
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [56]:
# Atribui nomes aos níveis do MultiIndex
# O primeiro nível (G1, G2) passa a se chamar 'Grupo'
# O segundo nível (1, 2, 3) passa a se chamar 'Numero'
df.index.names = ['Grupo', 'Numero']

In [57]:
# Exibe 'df'
df

                     A         B
Grupo Numero
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [58]:
# Extrai uma seção transversal do DataFrame
# Pega todas as linhas onde o nível 'Numero' é igual a 1, 
# atravessando todos os grupos do nível superior ('G1', 'G2', etc.)
df.xs(1, level='Numero')

              A         B
Grupo
G1     0.302665  1.693723
G2     0.166905  0.184502

Video: Dados Ausentes

In [59]:
# Cria um dicionário onde:
# 'A' tem um valor faltante
# 'B' tem dois valores faltantes
# 'C' está completo
d = {'A':[1, 2, np.nan], 'B':[5, np.nan, np.nan], 'C':[1, 2, 3]}

In [60]:
# Exibe 'd'
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [61]:
# Converte o dicionário 'd' em um DataFrame
# As chaves ('A', 'B', 'C') viram colunas e as listas viram as linhas
df = pd.DataFrame(d)

In [62]:
# Exibe 'df'
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [63]:
# Remove todas as linhas que possuem pelo menos um valor nulo (NaN)
df.dropna()

     A    B  C
0  1.0  5.0  1

In [64]:
# Mantém apenas as linhas que possuem, no mínimo, 2 valores NÃO-NULOS
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [65]:
# Substitui todos os valores nulos (NaN) pela string 'fill na'
df.fillna(value='fill na')

         A        B  C
0      1.0      5.0  1
1      2.0  fill na  2
2  fill na  fill na  3

In [66]:
# Preenche os valores nulos da coluna 'A' especificamente
# O valor usado para preencher é a média aritmética dos valores existentes na coluna 'A'
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [67]:
# Preenche os valores nulos (NaN) com o último valor válido encontrado anteriormente
# Ele "propaga" o dado de cima para baixo
df.ffill()

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

In [68]:
# Exibe 'df'
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

Video: GroupBy

In [69]:
# Cria um dicionário com informações de vendas por empresa e funcionário
data = {'Empresa':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Nome':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Venda':[200,120,340,124,243,350]}

In [70]:
# Transforma o dicionário 'data' em um DataFrame estruturado
df = pd.DataFrame(data)

In [71]:
# Exibe 'df'
df

  Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [72]:
# Cria um objeto GroupBy, agrupando os dados pela coluna 'Empresa'
# O Pandas agora sabe que 'GOOG', 'MSFT' e 'FB' são categorias distintas
group = df.groupby('Empresa')

In [73]:
# Soma todos os valores das colunas numéricas para cada grupo (Empresa)
# O parâmetro numeric_only=True garante que o Pandas não tente somar 
# a coluna 'Nome' (que contém texto)
group.sum(numeric_only=True)

         Venda
Empresa
FB         593
GOOG       320
MSFT       464

In [74]:
# Calcula a média das colunas numéricas (Venda) para cada Empresa
# numeric_only=True: Ignora a coluna 'Nome' pois não se tira média de texto
group.mean(numeric_only=True)

         Venda
Empresa
FB       296.5
GOOG     160.0
MSFT     232.0

In [75]:
# Gera um resumo estatístico detalhado para cada grupo (Empresa)
# Inclui: contagem, média, desvio padrão, valor mínimo, quartis e valor máximo
group.describe()

        Venda
        count   mean         std    min     25%    50%     75%    max
Empresa
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [76]:
# Agora o Pandas organiza os baldes baseados no nome do funcionário
group = df.groupby('Nome')

In [77]:
# Soma os valores numéricos agrupados por 'Nome'
# Como cada nome é único, o resultado mostra a venda individual de cada um,
# mas agora usando o Nome como o índice da tabela.
group.sum(numeric_only=True)

         Venda
Nome
Amy        340
Carl       243
Charlie    120
Sam        200
Sarah      350
Vanessa    124

In [78]:
# 1. Agrupa por 'Nome'
# 2. Soma os valores (numeric_only=True)
# 3. Localiza (.loc) a linha onde o índice é 'Amy'
group.sum(numeric_only=True).loc['Amy']

Venda    340
Name: Amy, dtype: int64

Video: Concatenar, Juntar e Mesclar

In [79]:
# Cria o primeiro DataFrame (df1) com 4 colunas (A, B, C, D) e 4 linhas
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [80]:
# Cria o segundo DataFrame (df2)
# Mantém as mesmas colunas (A, B, C, D) para garantir o alinhamento
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [81]:
# Cria o terceiro DataFrame (df3)
# Mantém as mesmas colunas (A, B, C, D) para garantir o alinhamento
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [82]:
# Exibe 'df1'
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [83]:
# Exibe 'df2'
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [84]:
# Exibe 'df3'
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [85]:
# Concatena (cola) os DataFrames df1, df2 e df3 um embaixo do outro
# O resultado é um único DataFrame com todas as 12 linhas
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [86]:
# Concatena os DataFrames horizontalmente (adicionando colunas)
# O Pandas tenta alinhar as linhas que possuem o mesmo índice
pd.concat([df1,df2,df3],axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [87]:
# DataFrame da esquerda: contém as colunas A, B e a chave de ligação
esquerda = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

# DataFrame da direita: contém as colunas C, D e a mesma chave de ligação
direita = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [88]:
# Exibe 'esquerda'
esquerda

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [89]:
# Exibe 'direita'
direita

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [90]:
# Realiza o merge (união) focando apenas no que é comum aos dois lados
# esquerda: O DataFrame base
# direita: O DataFrame que será acoplado
# how='inner': Mantém apenas as chaves que dão "match" em ambos
# on='key': A coluna que serve de ponte entre as tabelas
pd.merge(esquerda,direita,how='inner',on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [91]:
# DataFrames com chaves compostas
esquerda = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
direita = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [92]:
# Realiza a união baseada na combinação obrigatória de key1 e key2
pd.merge(esquerda, direita, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [93]:
# Realiza um Outer Join (União Externa)
# Mantém todas as chaves de ambos os DataFrames
pd.merge(esquerda, direita, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [94]:
# Realiza um Right Join (União à Direita)
# Preserva todas as combinações de chaves do DataFrame 'direita'
pd.merge(esquerda, direita, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [95]:
# Realiza um Left Join (União à Esquerda)
# Preserva todas as linhas do DataFrame 'esquerda'
pd.merge(esquerda, direita, how='left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [96]:
# DataFrame da esquerda: Chaves K0, K1, K2 no índice
esquerda = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

# DataFrame da direita: Chaves K0, K2, K3 no índice
direita = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [97]:
# Exibe 'esquerda'
esquerda

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [98]:
# Exibe 'direita'
direita

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [99]:
# O join utiliza os índices ('K0', 'K1', 'K2') por padrão
esquerda.join(direita)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [100]:
# Realiza o Outer Join usando os índices
# Resultado: Uma tabela que inclui K0, K1, K2 e K3
esquerda.join(direita, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

Video: Operações

In [134]:
# Criando um DataFrame de exemplo com números e strings
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

# Exibe as 5 primeiras linhas
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [102]:
# Retorna os valores sem repetição da col2
df['col2'].unique()

array([444, 555, 666])

In [103]:
# Usa o NumPy para extrair valores únicos
np.unique(df['col2'])

array([444, 555, 666])

In [104]:
# Retorna a quantidade de elementos únicos (3)
len(np.unique(df['col2']))

3

In [105]:
# Retorna o número de itens exclusivos (444, 555, 666)
df['col2'].nunique()

3

In [106]:
# Conta quantas vezes cada valor aparece na coluna
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [107]:
# Filtra o DataFrame usando duas condições:
# 1. col1 deve ser maior que 2 (Ex: 3, 4...)
# 2. col2 deve ser exatamente 444
# O operador '&' garante que AMBAS as condições sejam verdadeiras.
df[(df['col1'] > 2) & (df['col2'] == 444)]

   col1  col2 col3
3     4   444  xyz

In [108]:
# Função que dobra o valor de entrada
def vezes2(x):
    return x*2

In [109]:
# Soma todos os valores do DataFrame
df.sum()

col1              10
col2            2109
col3    abcdefghixyz
dtype: object

In [110]:
# A função 'apply' percorre a 'col1' elemento por elemento.
# Para cada valor, ela chama a função 'vezes2' e passa o valor como argumento.
# Exemplo: o valor 1 entra na função, e o apply recebe 2 de volta.
df['col1'].apply(vezes2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [111]:
# Calcula o comprimento (número de caracteres) de cada item na col3
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [112]:
# Eleva cada elemento da 'col1' ao quadrado
df['col1'].apply(lambda x : x*x)

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [113]:
# Remove a coluna 'col2' permanentemente do DataFrame
del df['col2']

In [114]:
# Exibe 'df'
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [115]:
# Retorna os nomes das colunas atuais do DataFrame
df.columns

Index(['col1', 'col3'], dtype='str')

In [116]:
# Mostra o identificador de cada linha.
df.index

RangeIndex(start=0, stop=4, step=1)

In [117]:
# Exibe 'df'
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [135]:
# Ordena o DataFrame com base nos valores da coluna
df.sort_values(by='col2')

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [ ]:
# Mapeia valores nulos em todo o DataFrame
df.isnull()

In [ ]:
# Remove todas as linhas que possuem valores ausentes (NaN)
df.dropna()

In [ ]:
# Criando um DataFrame com dados faltantes
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
# Exibe 'df'
df

In [ ]:
# Substitui os valores nulos (NaN) da 'col1' pela média aritmética da própria coluna.
df['col1'].fillna(value=df['col1'].mean())

In [119]:
# Cria um dicionario
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

# Converte o dicionario em um dataframe
df = pd.DataFrame(data)

In [120]:
# Exibe 'df'
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [121]:
# Reestrutura o DataFrame:
# Linhas (Index): Agrupa por 'A' e 'B', criando uma hierarquia de categorias.
# Colunas (Columns): Transpõe os valores únicos de 'C' para o cabeçalho.
# Valores (Values): Extrai dados de 'D' para preencher as células.
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

Video: Entrada e Saída de dados

In [122]:
# Carrega dados a partir de um arquivo CSV:
df = pd.read_csv('exemplo', sep=',')

In [123]:
# Exibe 'df'
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [124]:
# Incrementa todos os valores numéricos do DataFrame em 1
df = df + 1

In [125]:
# Exibe 'df'
df

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [126]:
# Exporta o DataFrame para um arquivo CSV
df.to_csv('exemplo.csv', sep=';', decimal=',')

In [127]:
# Importa uma aba específica de um arquivo Excel (.xlsx ou .xls):
df = pd.read_excel('Exemplo_Excel.xlsx', sheet_name='Sheet1')

In [128]:
# Exibe 'df'
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [129]:
# Salva o DataFrame em um arquivo Excel (.xlsx):
df.to_excel('exemplo.xlsx', sheet_name='Sheet1')

In [130]:
# Realiza Web Scraping para extrair tabelas de uma página HTML
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [131]:
# Verifica o tipo de dado da variável 'df'
type(df)

list

In [132]:
# Retorna a quantidade total de linhas (registros) presentes no DataFrame.
len(df)

1

In [133]:
# Acessa o primeiro elemento da lista retornada pelo read_html
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524