In [2]:
# Chamo a biblioteca 'numpy' e a apelido de 'np'
import numpy as np

# Chamo a biblioteca 'pandas' e a apelido de 'pd'
import pandas as pd

Video: Series

In [2]:
# Crio uma lista de strings
labels = ['a', 'b', 'c']

In [3]:
# Crio uma lista de inteiros
minha_lista = [10, 20, 30]

# Crio um array numpy, usando uma lista
arr = np.array([10, 20, 30])

# Crio um dicionário
d = {'a':10, 'b':20, 'c':30}

In [4]:
# Cria uma Series usando a lista como valores e 'labels' como índice
pd.Series(data=minha_lista, index = labels)

a    10
b    20
c    30
dtype: int64

In [5]:
# Armazeno a Series criada na variável 'series'
series = pd.Series(data=minha_lista, index = labels)

In [6]:
# Acesso o valor associado ao índice 'b' dentro da Series
series['b']

np.int64(20)

In [7]:
# Cria uma Series usando 'arr' como dados e 'labels' como índice
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [8]:
# Crio uma Series chamada 'ser1' onde os dados são números inteiros e os índices são nomes de países
ser1 = pd.Series([1, 2, 3, 4], index=['EUA', 'Alemanha', 'URSS', 'Japão'])

In [9]:
# Exibo 'ser1'
ser1

EUA         1
Alemanha    2
URSS        3
Japão       4
dtype: int64

In [10]:
# Crio uma segunda Series 'ser2'
ser2 = pd.Series([1, 2, 3, 4], index=['Alemanha', 'EUA', 'Itália', 'Japão'])

In [11]:
# Exibo 'ser2'
ser2

Alemanha    1
EUA         2
Itália      3
Japão       4
dtype: int64

In [12]:
# Realiza a soma das duas Series
ser1 + ser2

Alemanha    3.0
EUA         3.0
Itália      NaN
Japão       8.0
URSS        NaN
dtype: float64

Video: DataFrame - Criação e Fatiamento

In [13]:
# Seed para gerar os mesmos números aleátorios do video
np.random.seed(101)

In [14]:
# Crio um DataFrame com números aleatórios
# com 5 linhas (A a E) e 4 colunas (W a Z)
df = pd.DataFrame(np.random.randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split())

In [15]:
# Exibo 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [16]:
# Busco a coluna 'W' do DataFrame
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [17]:
# Busco o tipo de 'df['W']'
type(df['W'])

pandas.Series

In [18]:
# Busco o tipo de 'df'
type(df)

pandas.DataFrame

In [19]:
# Busco as colunas 'W' e 'Z' de 'df'
df[['W', 'Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [20]:
# Outra jeito de buscar uma coluna de um dataframe
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [21]:
# Crio uma nova coluna chamada 'new', onde cada valor é a soma dos elementos das colunas 'W' e 'X'
df['new'] = df['W'] + df['X']

In [22]:
# Exibo 'df'
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [23]:
# Removo a coluna 'new'
df.drop('new', axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
# Exibo 'df'
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [25]:
# Removo a coluna 'new' permanentemente
df.drop('new', axis=1, inplace=True)

In [26]:
# Exibo 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [27]:
# Seleciono a linha 'A'
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [28]:
# Busco do dados presentes nas linhas 'A' e 'B' com as colunas 'X', 'Y' e 'Z'
df.loc[['A', 'B'], ['X', 'Y', 'Z']]

          X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965

In [29]:
# Busco os dados presentes nas linhas 'B', 'C' e 'D' com as colunas 'Y' e 'Z'
df.iloc[1:4, 2: ]

          Y         Z
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057

Video: DataFrame - Seleção condicional, set_index

In [30]:
# Exibo 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
# Filtro o df por dados maiores que zero
bool = df > 0

In [32]:
# Exibo o df com o filtro
df[bool]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [33]:
# Busco as linhas do 'df' em que o dado na coluna 'W' é maior que zero
df[df['W'] > 0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [34]:
# Busco os dados da coluna 'Y' em que os dados das linhas da coluna 'W' são maiores que zero
df[df['W'] > 0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [35]:
# Faz a mesma coisa que o codigo acima
bool = df['W'] > 0
df2 = df[bool]
df2['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [36]:
# Busco as linhas de 'W' são maiores que zero ou as linhas de 'Y' são maiores que um
df[(df['W'] > 0) | (df['Y'] > 1)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
# Exibo 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [38]:
# Redefino o índices do 'df' para números inteiros (0, 1, 2...)
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [39]:
# Exibo 'df'
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
# Defino nomes das colunas
col = 'RS RJ SP AM SC'.split()

In [41]:
# Exibo 'col'
col

['RS', 'RJ', 'SP', 'AM', 'SC']

In [42]:
# Crio uma nova coluna 'Estado' e a preencho com os dados 'col'
df['Estado'] = col

In [43]:
# Exibo 'df'
df

          W         X         Y         Z Estado
A  2.706850  0.628133  0.907969  0.503826     RS
B  0.651118 -0.319318 -0.848077  0.605965     RJ
C -2.018168  0.740122  0.528813 -0.589001     SP
D  0.188695 -0.758872 -0.933237  0.955057     AM
E  0.190794  1.978757  2.605967  0.683509     SC

In [44]:
# Defino a coluna 'Estado' como o novo índice do 'df'
df.set_index('Estado')

               W         X         Y         Z
Estado
RS      2.706850  0.628133  0.907969  0.503826
RJ      0.651118 -0.319318 -0.848077  0.605965
SP     -2.018168  0.740122  0.528813 -0.589001
AM      0.188695 -0.758872 -0.933237  0.955057
SC      0.190794  1.978757  2.605967  0.683509

In [45]:
# Exibo 'df'
df

          W         X         Y         Z Estado
A  2.706850  0.628133  0.907969  0.503826     RS
B  0.651118 -0.319318 -0.848077  0.605965     RJ
C -2.018168  0.740122  0.528813 -0.589001     SP
D  0.188695 -0.758872 -0.933237  0.955057     AM
E  0.190794  1.978757  2.605967  0.683509     SC

Video: DataFrame - Índices Multiníveis

In [46]:
# Cria duas listas que servirão como níveis do índice
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]

# Junto as duas listas, e obtendo uma lista de tuplas: [('G1', 1), ('G1', 2), ..., ('G2', 3)]
hier_index = list(zip(outside, inside))

# Possibilita a criação de um subindice
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [47]:
# Exibo 'outside'
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [48]:
# Exibo 'inside'
inside

[1, 2, 3, 1, 2, 3]

In [49]:
# Junto as duas listas, e obtendo uma lista de tuplas: [('G1', 1), ('G1', 2), ..., ('G2', 3)]
hier_index = list(zip(outside, inside))

In [50]:
# Exibo 'hier_index'
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [51]:
# Possibilita a criação de um subindice 
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [52]:
# Exibo 'hier_index'
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [53]:
# Cria um dataframe de 6 linhas e 2 colunas com números aleatórios
# tendo como indices o 'hier_index'
# e como colunas 'A' e 'B'
df = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns=['A', 'B'])

In [54]:
# Exibo 'df'
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [55]:
# Busco os dados da linha do subindice '1' presentes no indice 'G1'
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [56]:
# Renomeio os nomes do indice e do subindice
# o do indice para 'Grupo' e o do subindice para 'Numero'
df.index.names = ['Grupo', 'Numero']

In [57]:
# Exibo 'df'
df

                     A         B
Grupo Numero
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [58]:
# Busco os dados presentes no subindice 1 dos indices 'G1' e 'G2'
df.xs(1, level='Numero')

              A         B
Grupo
G1     0.302665  1.693723
G2     0.166905  0.184502

Video: Dados Ausentes

In [59]:
# Crio um dicionário
d = {'A':[1, 2, np.nan], 'B':[5, np.nan, np.nan], 'C':[1, 2, 3]}

In [60]:
# Exibo 'd'
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [61]:
# Converto o dicionário 'd' em um dataframe
df = pd.DataFrame(d)

In [62]:
# Exibo 'df'
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [63]:
# Removo as linhas que possuem pelo menos um dado nulo (NaN)
df.dropna()

     A    B  C
0  1.0  5.0  1

In [64]:
# Mantenho apenas as linhas que possuem, no mínimo, 2 dados NÃO-NULOS
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [65]:
# Substituo todos os dados nulos pela string 'fill na'
df.fillna(value='fill na')

         A        B  C
0      1.0      5.0  1
1      2.0  fill na  2
2  fill na  fill na  3

In [66]:
# Preencho os dados nulos da coluna 'A' com a média aritmética de seus dados não nulos
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [67]:
# Preencho os dados nulos com o último dado não nulo encontrado
df.ffill()

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

In [68]:
# Exibo 'df'
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

Video: GroupBy

In [69]:
# Crio um dicionário
data = {'Empresa':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Nome':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Venda':[200,120,340,124,243,350]}

In [70]:
# Converto o dicionário 'data' em um dataframe
df = pd.DataFrame(data)

In [71]:
# Exibo 'df'
df

  Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [72]:
# Agrupo por empresas
group = df.groupby('Empresa')

In [73]:
# Agora chamo a função 'sum' para saber o total de venda em cada empresa
group.sum(numeric_only=True)

         Venda
Empresa
FB         593
GOOG       320
MSFT       464

In [74]:
# Agora calculo a média de vendas em cada empresa
group.mean(numeric_only=True)

         Venda
Empresa
FB       296.5
GOOG     160.0
MSFT     232.0

In [75]:
# chamo a função 'describe' para gerar informações estatísticas de cada empresa
group.describe()

        Venda
        count   mean         std    min     25%    50%     75%    max
Empresa
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [76]:
# Agora agrupo por nomes
group = df.groupby('Nome')

In [77]:
# Chamo a função 'sum' para buscar as vendas de cada pessoa
group.sum(numeric_only=True)

         Venda
Nome
Amy        340
Carl       243
Charlie    120
Sam        200
Sarah      350
Vanessa    124

In [78]:
# Aqui eu busco a venda total de uma pessoa em específico
group.sum(numeric_only=True).loc['Amy']

Venda    340
Name: Amy, dtype: int64

Video: Concatenar, Juntar e Mesclar

In [3]:
# Crio o 'df1'
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [4]:
# Crio o 'df2'
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [5]:
# Crio o 'df3'
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [6]:
# Exibo 'df1'
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [7]:
# Exibo 'df2'
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [8]:
# Exibo 'df3'
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [9]:
# Aqui eu junto os três dfs
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [11]:
# Desta vez eu junto os dfs pelos indices
# se os indices nao coincidirem, o resultado vai ser NaN
pd.concat([df1,df2,df3],axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [26]:
# Crio o dataframe 'esquerda'
esquerda = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

# Crio o dataframe 'direita'
direita = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [27]:
# Exibo 'esquerda'
esquerda

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [28]:
# Exibo 'direita'
direita

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [29]:
# Junto os dois dataframes pela coluna 'key'
pd.merge(esquerda,direita,how='inner',on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [30]:
# Crio dataframes com chaves compostas

In [31]:

esquerda = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

In [32]:
direita = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [33]:
esquerda

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [34]:
direita

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [92]:
# Junto os dois dfs onde 'key1' e 'key2' são iguais
pd.merge(esquerda, direita, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [37]:
# Junto os dois dfs por 'key1' e 'key2', mantendo todas as linhas de ambos dfs
# e onde não houver correspondência, o resultado é NaN
pd.merge(esquerda, direita, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [36]:
# Mantenho todas as linhas do df da direita
# e onde não tiver correspondência na esquerda, o resultado é NaN
pd.merge(esquerda, direita, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [95]:
# Mantenho todas as linhas do df da esquerda
# e onde não tiver correspondência na direita, o resultado é NaN
pd.merge(esquerda, direita, how='left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [38]:
# Crio dois dataframes
esquerda = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

direita = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [39]:
# Exibo 'esquerda'
esquerda

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [40]:
# Exibo 'direita'
direita

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [99]:
# Junto os dfs pelo indices
# mantém tudo o que está na esquerda, e procura na direita
esquerda.join(direita)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [100]:
# Junto os dois dfs, sem perder linhas de ambos
# e se o indice existir só em um df, aparece NaN no outro
esquerda.join(direita, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

Video: Operações

In [65]:
# Crio um df
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

# Exibo suas 5 primeiras linhas
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [43]:
# Busco os dados sem repetiçãoda da 'col2'
df['col2'].unique()

array([444, 555, 666])

In [44]:
# Retorna a mesma coisa que o código acima
np.unique(df['col2'])

array([444, 555, 666])

In [45]:
# Retorna a quantidade de dados únicos de 'col2'
len(np.unique(df['col2']))

3

In [105]:
# Retorna o número de itens exclusivos (444, 555, 666)
df['col2'].nunique()

3

In [46]:
# Busco a quantidade de vezes que cada dado aparece na 'col2'
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [47]:
# Busco os dados presentes na 'col1' que são maiores que 2 e na 'col2' em que o dado é igual a 444
# isto me retorna a linha onde estes critérios são satisfeitos
df[(df['col1'] > 2) & (df['col2'] == 444)]

   col1  col2 col3
3     4   444  xyz

In [48]:
# Função que dobra o valor de entrada
def vezes2(x):
    return x*2

In [54]:
# Somo todos os valores do DataFrame
df.sum()

col1              10
col2            2109
col3    abcdefghixyz
dtype: object

In [55]:
# Aplico a função 'vezes2' nos dados da 'col1'
df['col1'].apply(vezes2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [56]:
# Calculo o comprimento de cada dado da 'col3'
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [57]:
# Elevo cada elemento da 'col1' ao quadrado
df['col1'].apply(lambda x : x*x)

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [58]:
# Removo a coluna 'col2' permanentemente do DataFrame
del df['col2']

In [60]:
# Exibo 'df'
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [61]:
# Retorna os nomes das colunas atuais do DataFrame
df.columns

Index(['col1', 'col3'], dtype='str')

In [62]:
# Mostra os indices do df
df.index

RangeIndex(start=0, stop=4, step=1)

In [63]:
# Exibo 'df'
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [66]:
# Ordeno o dataframe com base nos valores da coluna
df.sort_values(by='col2')

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [68]:
# Para saber os dados nulos do df
df.isnull()

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [69]:
# Removo todas as linhas que possuem dados nulos (NaN)
df.dropna()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [70]:
# Crio um df
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
# Exibe 'df'
df

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [71]:
# Preencho os dados nulos presentes na 'col1' com a média de seus dados
df['col1'].fillna(value=df['col1'].mean())

0    1.0
1    2.0
2    3.0
3    2.0
Name: col1, dtype: float64

In [72]:
# Crio um dicionario
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

# Converto o dicionario em um dataframe
df = pd.DataFrame(data)

In [73]:
# Exibo 'df'
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [74]:
# Reorganizo todo o dataframe
# com os valores de 'D'
# indices 'A' e 'B'
# e coluna 'C'
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

Video: Entrada e Saída de dados

In [76]:
# Carrego um arquivo CSV:
df = pd.read_csv('exemplo', sep=',')

In [77]:
# Exibo 'df'
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [78]:
# Incremento todos os valores numéricos do df em 1
df = df + 1

In [79]:
# Exibo 'df'
df

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [81]:
# Exporta o df para um arquivo csv
df.to_csv('exemplo.csv', sep=';', decimal=',')

In [82]:
# Carrego uma aba específica do aruivo
df = pd.read_excel('Exemplo_Excel.xlsx', sheet_name='Sheet1')

In [83]:
# Exibo 'df'
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [84]:
# Salvo o df em xlsx
df.to_excel('exemplo.xlsx', sheet_name='Sheet1')

In [85]:
# Web Scraping para extrair tabelas de uma página HTML
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [86]:
# Verifica o tipo de dado da variável 'df'
type(df)

list

In [87]:
# Retorna a quantidade total de linhas (registros) presentes no DataFrame.
len(df)

1

In [89]:
# Acesso o primeiro elemento da lista retornada pelo read_html
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524