Exercicios de numpy

In [52]:
# Importa a biblioteca NumPy e a apelida como 'np'
import numpy as np

1. Crie um array 3x3 contendo apenas números ímpares de 1 a 17

In [53]:
# 1. np.arange(1, 18, 2): Gera números de 1 até 17 (o 18 é exclusivo), pulando de 2 em 2.
# 2. .reshape(3, 3): Reorganiza esses 9 elementos em um formato de 3 linhas e 3 colunas.
exercicio_1 = np.arange(1, 18, 2).reshape(3, 3)

In [54]:
# Exibe 'exercicio_1
exercicio_1

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

2. Manipulação de Shape: Crie um vetor de 20 elementos aleatórios entre 0 e 1 e transforme-o em uma matriz 4x5.

In [56]:
# 1. np.random.random(20): Gera um array unidimensional com 20 números flutuantes (float) no intervalo entre 0.0 e 1.0.
# 2. .reshape(4, 5): Reorganiza esses 20 números em 4 linhas e 5 colunas.
exercicio_2 = np.random.random(20).reshape(4, 5)

In [57]:
# Exibe 'exercicio_2'
exercicio_2

array([[0.08242441, 0.81560904, 0.50915451, 0.30643435, 0.88237005],
       [0.02814513, 0.39402301, 0.53339618, 0.9057316 , 0.59529337],
       [0.24924332, 0.55715348, 0.76249   , 0.7559366 , 0.30184683],
       [0.52297896, 0.17489169, 0.9918612 , 0.43373536, 0.65768475]])

3. Dado o array arr = np.array([10, 20, 30, 40, 50]), substitua todos os valores maiores que 30 por -1.

In [60]:
# Cria um array com 5 elementos inteiros
arr = np.array([10, 20, 30, 40, 50])

# Aplica um boolea para filtragem e substituição:
# 1. arr > 30: Cria uma lista de True/False ([False, False, False, True, True]).
# 2. arr[...]: Seleciona apenas os elementos onde a condição é True (40 e 50).
# 3. = -1: Atribui o valor -1 a esses elementos selecionados.
arr[arr > 30] = -1

In [61]:
# Exibe 'arr'
arr

array([10, 20, 30, -1, -1])

4. Operações Estatísticas: Crie uma matriz 5x5 de números inteiros aleatórios e calcule:

A média de cada coluna.
O valor máximo de cada linha.

In [65]:
# Cria uma matriz 5x5 preenchida com números inteiros aleatórios entre 0 e 99.
matriz = np.random.randint(0, 100, (5, 5))

# Calcula a média aritmética de cada coluna, axis=0
# O resultado será um array com 5 valores (um para cada coluna).
media_colunas = matriz.mean(axis=0)

# Identifica o valor máximo de cada linha, axis=1
# O resultado será um array com 5 valores (o maior de cada uma das 5 linhas).
max_linhas = matriz.max(axis=1)

In [66]:
# Exibe 'matriz'
matriz

array([[68, 55, 92, 26, 94],
       [19, 30, 59, 86, 19],
       [55, 81, 29, 49, 86],
       [70, 74, 84, 59, 19],
       [73, 92, 47, 20, 58]], dtype=int32)

In [67]:
# Exibe 'media_colunas'
media_colunas

array([57. , 66.4, 62.2, 48. , 55.2])

In [68]:
# Exibe 'max_linhas'
max_linhas

array([94, 86, 86, 84, 92], dtype=int32)

Exercicios de pandas

In [69]:
# Importa a biblioteca Pandas e a apelida como 'pd'.
import pandas as pd

In [70]:
# Definindo os dados base
dados = {
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo', 'Fernanda', 'Gabriel', 'Helena', 'Ítalo', 'Julia'],
    'Departamento': ['TI', 'RH', 'TI', 'Vendas', 'Financeiro', 'RH', 'Vendas', 'TI', 'Financeiro', 'TI'],
    'Salario': [8500, 4200, np.nan, 3500, 6000, np.nan, 3800, 10500, 5800, 7200],
    'Anos_Empresa': [5, 2, 8, 1, 4, 3, 2, 10, 5, 6]
}

In [71]:
# Criando o DataFrame
df = pd.DataFrame(dados)

In [73]:
# Exibe 'df'
df

       Nome Departamento  Salario  Anos_Empresa
0       Ana           TI   8500.0             5
1     Bruno           RH   4200.0             2
2    Carlos           TI      NaN             8
3   Daniela       Vendas   3500.0             1
4   Eduardo   Financeiro   6000.0             4
5  Fernanda           RH      NaN             3
6   Gabriel       Vendas   3800.0             2
7    Helena           TI  10500.0            10
8     Ítalo   Financeiro   5800.0             5
9     Julia           TI   7200.0             6

5. Selecione apenas os funcionários do departamento 'TI' que ganham mais de R$ 5.000

In [74]:
# 1. (df['Departamento'] == 'TI'): Cria um boolean para quem é do setor de TI.
# 2. (df['Salario'] > 5000): Cria um boolean para salários maiores que 5000.
# 3. &: O operador 'E' lógico exige que AMBAS as condições sejam verdadeiras.
# 4. df[...]: Aplica o filtro final, retornando apenas as linhas que atendem aos critérios.
ti_bem_pago = df[(df['Departamento'] == 'TI') & (df['Salario'] > 5000)]

In [76]:
# Exibe 'ti_bem_pago'
ti_bem_pago

     Nome Departamento  Salario  Anos_Empresa
0     Ana           TI   8500.0             5
7  Helena           TI  10500.0            10
9   Julia           TI   7200.0             6

6. Calcule a média salarial por departamento

In [78]:
# 1. .groupby('Departamento'): Divide o DataFrame em grupos baseados nos valores da coluna 'Departamento'.
# 2. ['Salario']: Seleciona apenas a coluna de salários dentro de cada grupo para o cálculo.
# 3. .mean(): Aplica a função de média aritmética para cada um desses grupos.
media_departamento = df.groupby('Departamento')['Salario'].mean()

In [79]:
# Exibe 'media_departamento
media_departamento

Departamento
Financeiro    5900.000000
RH            4200.000000
TI            8733.333333
Vendas        3650.000000
Name: Salario, dtype: float64

7. Identifique se existem valores nulos no DataFrame. Substitua os valores nulos da coluna Salario pela mediana dos salários

In [23]:
# Identificar os nulos
nulos = df.isna().sum()

In [80]:
# Exibe 'nulos'
nulos

Nome            0
Departamento    0
Salario         2
Anos_Empresa    0
dtype: int64

In [81]:
# Substituir pela mediana:
mediana = df['Salario'].median()

# Preenche os valores nulos (vazios) da coluna 'Salario' com a mediana calculada.
# O método .fillna() substitui entradas NaN pelo valor fornecido 
# e o resultado é atribuído de volta à coluna original para salvar as alterações.
df['Salario'] = df['Salario'].fillna(mediana)

# Exibe 'df'
df

       Nome Departamento  Salario  Anos_Empresa
0       Ana           TI   8500.0             5
1     Bruno           RH   4200.0             2
2    Carlos           TI   5900.0             8
3   Daniela       Vendas   3500.0             1
4   Eduardo   Financeiro   6000.0             4
5  Fernanda           RH   5900.0             3
6   Gabriel       Vendas   3800.0             2
7    Helena           TI  10500.0            10
8     Ítalo   Financeiro   5800.0             5
9     Julia           TI   7200.0             6

8. Crie uma nova coluna chamada Bonus, que corresponde a 10% do salário para quem tem mais de 5 anos de empresa e 5% para os demais

In [82]:
# Cria uma nova coluna 'Bonus' baseada no tempo de empresa do funcionário.
# np.where(condição, valor_se_verdadeiro, valor_se_falso):
# 1. df['Anos_Empresa'] > 5: A condição a ser testada (mais de 5 anos de empresa).
# 2. df['Salario'] * 0.10: O que acontece se for True (bônus de 10%).
# 3. df['Salario'] * 0.05: O que acontece se for False (bônus de 5%).
df['Bonus'] = np.where(df['Anos_Empresa'] > 5, df['Salario'] * 0.10, df['Salario'] * 0.05)

In [83]:
# Exibe 'df'
df

       Nome Departamento  Salario  Anos_Empresa   Bonus
0       Ana           TI   8500.0             5   425.0
1     Bruno           RH   4200.0             2   210.0
2    Carlos           TI   5900.0             8   590.0
3   Daniela       Vendas   3500.0             1   175.0
4   Eduardo   Financeiro   6000.0             4   300.0
5  Fernanda           RH   5900.0             3   295.0
6   Gabriel       Vendas   3800.0             2   190.0
7    Helena           TI  10500.0            10  1050.0
8     Ítalo   Financeiro   5800.0             5   290.0
9     Julia           TI   7200.0             6   720.0

9. Mostre os 3 funcionários mais bem pagos da empresa.

In [84]:
# 1. .sort_values(by='Salario'): Define que a ordenação será baseada na coluna 'Salario'.
# 2. ascending=False: Define a ordem decrescente (do maior para o menor). 
# 3. .head(3): Após ordenar, seleciona apenas as 3 primeiras linhas do resultado.
df.sort_values(by='Salario', ascending=False).head(3)

     Nome Departamento  Salario  Anos_Empresa   Bonus
7  Helena           TI  10500.0            10  1050.0
0     Ana           TI   8500.0             5   425.0
9   Julia           TI   7200.0             6   720.0

Exercicios de numpy e pandas

10. Crie uma matriz NumPy 10x4 com números aleatórios simulando notas de 4 provas para 10 alunos

In [46]:
# Gera floats entre 0 e 10 para 10 linhas e 4 colunas
notas = np.random.uniform(0, 10, (10, 4))
notas

array([[1.18544746, 9.82217669, 2.8504275 , 8.35593992],
       [3.11048181, 4.69828336, 6.71355479, 7.15328419],
       [7.98118701, 0.13161764, 0.42008102, 1.92008919],
       [7.62884491, 8.83578383, 7.46050755, 9.98767661],
       [4.6301463 , 0.14051895, 1.44730887, 8.12164317],
       [5.23555594, 1.46613723, 8.96504364, 4.94631054],
       [5.32642904, 3.83745257, 3.7439951 , 2.09399068],
       [1.98361322, 4.71974855, 8.09952417, 8.86682393],
       [5.38553425, 5.77320128, 6.27605716, 0.30529634],
       [5.79648667, 3.99829956, 2.13786075, 5.72302191]])

11. Converta essa matriz em um DataFrame do Pandas

In [47]:
# Definimos nomes para as colunas
provas = ['Prova_1', 'Prova_2', 'Prova_3', 'Prova_4']
df_alunos = pd.DataFrame(notas, columns=provas)

# Exibe 'df_alunos'
df_alunos

    Prova_1   Prova_2   Prova_3   Prova_4
0  1.185447  9.822177  2.850428  8.355940
1  3.110482  4.698283  6.713555  7.153284
2  7.981187  0.131618  0.420081  1.920089
3  7.628845  8.835784  7.460508  9.987677
4  4.630146  0.140519  1.447309  8.121643
5  5.235556  1.466137  8.965044  4.946311
6  5.326429  3.837453  3.743995  2.093991
7  1.983613  4.719749  8.099524  8.866824
8  5.385534  5.773201  6.276057  0.305296
9  5.796487  3.998300  2.137861  5.723022

12. Adicione uma coluna chamada Media calculando a média das notas de cada aluno

In [48]:
# Coluna chamada "Media" calculando a média das notas de cada aluno
# axis=1 indica que queremos a média na horizontal (por linha/aluno)
df_alunos['Media'] = df_alunos.mean(axis=1)

# Exibe 'df_alunos'
df_alunos

    Prova_1   Prova_2   Prova_3   Prova_4     Media
0  1.185447  9.822177  2.850428  8.355940  5.553498
1  3.110482  4.698283  6.713555  7.153284  5.418901
2  7.981187  0.131618  0.420081  1.920089  2.613244
3  7.628845  8.835784  7.460508  9.987677  8.478203
4  4.630146  0.140519  1.447309  8.121643  3.584904
5  5.235556  1.466137  8.965044  4.946311  5.153262
6  5.326429  3.837453  3.743995  2.093991  3.750467
7  1.983613  4.719749  8.099524  8.866824  5.917427
8  5.385534  5.773201  6.276057  0.305296  4.435022
9  5.796487  3.998300  2.137861  5.723022  4.413917

13. Adicione uma coluna Status que diz "Aprovado" se a média for maior que 7 e "Reprovado" caso contrário

In [49]:
# Coluna "Status" (Aprovado >= 7 / Reprovado < 7)
# np.where(condição, se_verdadeiro, se_falso)
df_alunos['Status'] = np.where(df_alunos['Media'] >= 7, 'Aprovado', 'Reprovado')

In [50]:
# Exibe 'df_alunos'
df_alunos

    Prova_1   Prova_2   Prova_3   Prova_4     Media     Status
0  1.185447  9.822177  2.850428  8.355940  5.553498  Reprovado
1  3.110482  4.698283  6.713555  7.153284  5.418901  Reprovado
2  7.981187  0.131618  0.420081  1.920089  2.613244  Reprovado
3  7.628845  8.835784  7.460508  9.987677  8.478203   Aprovado
4  4.630146  0.140519  1.447309  8.121643  3.584904  Reprovado
5  5.235556  1.466137  8.965044  4.946311  5.153262  Reprovado
6  5.326429  3.837453  3.743995  2.093991  3.750467  Reprovado
7  1.983613  4.719749  8.099524  8.866824  5.917427  Reprovado
8  5.385534  5.773201  6.276057  0.305296  4.435022  Reprovado
9  5.796487  3.998300  2.137861  5.723022  4.413917  Reprovado