In [185]:
# chamo a biblioteca pandas e apelido de pd
import pandas as pd

In [186]:
# leio o arquivo .csv obtido no kaggle https://www.kaggle.com/datasets/showmik121/smartphones-dataset-2026-1000-devices
celulares = pd.read_csv('smartprix_smartphones_april_2026.csv')

In [187]:
# utilizo esta função do dataframe para saber quais informações me interessam
celulares.info()

<class 'pandas.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand_name             997 non-null    str
 1   model                  997 non-null    str
 2   price_category         997 non-null    str
 3   price                  997 non-null    int64
 4   spec_score             997 non-null    int64
 5   vfm_score              997 non-null    float64
 6   vfm_label              997 non-null    str
 7   has_5G                 997 non-null    bool
 8   has_NFC                997 non-null    bool
 9   has_IR                 997 non-null    bool
 10  processor_brand        996 non-null    str
 11  processor_name         997 non-null    str
 12  num_core               980 non-null    float64
 13  processor_speed        862 non-null    float64
 14  ram                    997 non-null    float64
 15  memory                 997 non-null    float64
 16  battery_capacity(mAh)  997 non-null    float64
 17  fast_charging(W)       941 non-null    float64
 18  charging_ratio         941 non-null    float64
 19  charging_speed_type    997 non-null    str
 20  screen_size            997 non-null    float64
 21  refresh_rate           948 non-null    float64
 22  rear_camera            981 non-null    float64
 23  front_camera           979 non-null    float64
 24  rear_camera_count      997 non-null    int64
 25  os                     986 non-null    str
dtypes: bool(3), float64(12), int64(3), str(8)
memory usage: 182.2 KB

In [188]:
# selecionei as informações que mem interessam
celulares = celulares[['brand_name', 'model', 'price', 'has_5G', 'processor_brand', 'processor_name', 'ram', 'memory']]

In [189]:
# Confirmo as alterações
celulares

,brand_name,model,price,has_5G,processor_brand,processor_name,ram,memory
0,oneplus,OnePlus Nord 6,38999,True,qualcomm,Snapdragon 8s Gen4,8.0,256.0
1,samsung,Samsung Galaxy S25 Ultra,110000,True,qualcomm,Snapdragon 8 Elite for Galaxy,12.0,256.0
2,vivo,Vivo T5 Pro,29999,True,qualcomm,Snapdragon 7s Gen4,8.0,128.0
3,samsung,Samsung Galaxy S25 FE,50743,True,samsung,Exynos 2400,8.0,128.0
4,vivo,Vivo T5x 5G,18999,True,mediatek,Dimensity 7400 Turbo,6.0,128.0
...,...,...,...,...,...,...,...,...
992,realme,Realme C85 5G (6GB RAM + 128GB),17999,True,mediatek,Dimensity 6300,6.0,128.0
993,vivo,Vivo X500,57990,True,mediatek,Dimensity 9600,12.0,256.0
994,vivo,Vivo Y19s 5G (4GB RAM + 128GB),13499,True,mediatek,Dimensity 6300,4.0,128.0
995,oukitel,Oukitel WP60 5G,24699,True,mediatek,Dimensity 7025,8.0,256.0
996,vivo,Vivo S50,39990,True,qualcomm,Snapdragon 8s Gen3,12.0,256.0

In [190]:
# renomeio a coluna 'price'
celulares = celulares.rename(columns={'price':'price (Indian Rupe)'})

In [191]:
# confirmo a alteração
celulares

,brand_name,model,price (Indian Rupe),has_5G,processor_brand,processor_name,ram,memory
0,oneplus,OnePlus Nord 6,38999,True,qualcomm,Snapdragon 8s Gen4,8.0,256.0
1,samsung,Samsung Galaxy S25 Ultra,110000,True,qualcomm,Snapdragon 8 Elite for Galaxy,12.0,256.0
2,vivo,Vivo T5 Pro,29999,True,qualcomm,Snapdragon 7s Gen4,8.0,128.0
3,samsung,Samsung Galaxy S25 FE,50743,True,samsung,Exynos 2400,8.0,128.0
4,vivo,Vivo T5x 5G,18999,True,mediatek,Dimensity 7400 Turbo,6.0,128.0
...,...,...,...,...,...,...,...,...
992,realme,Realme C85 5G (6GB RAM + 128GB),17999,True,mediatek,Dimensity 6300,6.0,128.0
993,vivo,Vivo X500,57990,True,mediatek,Dimensity 9600,12.0,256.0
994,vivo,Vivo Y19s 5G (4GB RAM + 128GB),13499,True,mediatek,Dimensity 6300,4.0,128.0
995,oukitel,Oukitel WP60 5G,24699,True,mediatek,Dimensity 7025,8.0,256.0
996,vivo,Vivo S50,39990,True,qualcomm,Snapdragon 8s Gen3,12.0,256.0

In [192]:
# quantidade de celulares por marca
celulares['brand_name'].value_counts()

brand_name
vivo        135
samsung     127
realme      127
oppo         90
xiaomi       72
motorola     58
oneplus      54
iqoo         47
poco         45
infinix      38
tecno        32
apple        31
honor        24
lava         19
google       19
nothing      18
ai+           9
nubia         8
huawei        7
itel          6
cmf           5
hmd           4
acer          3
wobble        3
red           2
sony          2
vertu         2
asus          2
redmagic      1
bluefox       1
samaung       1
peace         1
philips       1
nokia         1
tesla         1
oukitel       1
Name: count, dtype: int64

In [193]:
# preço medio por marca
celulares.groupby('brand_name')['price (Indian Rupe)'].mean().sort_values(ascending=False)

brand_name
vertu       457994.500000
sony        145490.000000
huawei      117847.142857
asus        107490.000000
apple       106286.870968
tesla        69999.000000
redmagic     69990.000000
google       69601.842105
red          53990.000000
samsung      46410.889764
honor        41827.083333
iqoo         41471.340426
oneplus      41301.296296
nubia        40867.250000
nothing      38800.611111
oppo         38570.966667
xiaomi       37077.638889
vivo         33764.148148
motorola     30004.275862
wobble       28332.333333
realme       25270.755906
nokia        24999.000000
oukitel      24699.000000
poco         23240.000000
cmf          19797.200000
tecno        19431.531250
infinix      18575.052632
ai+          14276.777778
lava         13663.210526
samaung      13200.000000
acer         12826.333333
philips      11990.000000
itel         10214.166667
hmd          10101.000000
bluefox       8699.000000
peace         5900.000000
Name: price (Indian Rupe), dtype: float64

In [194]:
# quantidade de precessadores por marca
celulares['processor_brand'].value_counts()

processor_brand
mediatek     445
qualcomm     346
samsung       66
unisoc        46
unknown       36
apple         30
google        19
hisilicon      7
dimensity      1
Name: count, dtype: int64

In [195]:
# média de preço por tipo de processador
celulares.groupby('processor_brand')['price (Indian Rupe)'].mean()

processor_brand
apple        103833.100000
dimensity     39990.000000
google        69601.842105
hisilicon    117847.142857
mediatek      25041.979775
qualcomm      49386.722543
samsung       40122.909091
unisoc        10330.130435
unknown       38244.750000
Name: price (Indian Rupe), dtype: float64

In [196]:
# relação ram x preço
celulares[['ram', 'price (Indian Rupe)']].corr()

                          ram  price (Indian Rupe)
ram                  1.000000             0.528438
price (Indian Rupe)  0.528438             1.000000

In [197]:
# a ram tem uma influência moderada em relação ao preço

In [198]:
# celulares que não possuem 5G
celulares[celulares['has_5G'] == False]

,brand_name,model,price (Indian Rupe),has_5G,processor_brand,processor_name,ram,memory
44,xiaomi,Xiaomi Redmi A7 Pro,13999,False,unisoc,Unisoc T7250,4.0,64.0
98,vivo,Vivo Y31d,11990,False,qualcomm,Snapdragon 6s Gen 2 4G,6.0,128.0
130,samsung,Samsung Galaxy F05,6499,False,mediatek,Helio G85,4.0,64.0
157,motorola,Motorola Moto G05,7299,False,mediatek,Helio G81 Ultra,4.0,64.0
161,samsung,Samsung Galaxy M14 4G,7773,False,qualcomm,Snapdragon 680,4.0,64.0
...,...,...,...,...,...,...,...,...
962,poco,Poco C65,8499,False,mediatek,Helio G85,4.0,128.0
979,realme,Realme 7,11999,False,mediatek,Helio G95,6.0,64.0
982,xiaomi,Xiaomi Redmi K20 Pro Signature Edition,480000,False,qualcomm,Snapdragon 855,8.0,256.0
987,realme,Realme P4 Lite 4G,10480,False,unisoc,Unisoc T7250,4.0,64.0
991,tecno,Tecno Spark GO 3,9990,False,unisoc,Unisoc T7250,4.0,64.0

In [199]:
# quantidade de celulares sem 5G
celulares_sem_5G = celulares[celulares['has_5G'] == False]
len(celulares_sem_5G)

70

In [200]:
# processador que aparece mais vezes
celulares['processor_name'].value_counts().idxmax()

'Dimensity 6300'

In [201]:
# esta função lambda cria uma nova coluna com base na coluna de memória ram
celulares['nivel_ram'] = celulares['ram'].apply(
    lambda x: 'baixa' if x <= 4 else 'media' if x <= 8 else 'alta'
)

In [202]:
# confirmo a alteração feita
celulares

,brand_name,model,price (Indian Rupe),has_5G,processor_brand,processor_name,ram,memory,nivel_ram
0,oneplus,OnePlus Nord 6,38999,True,qualcomm,Snapdragon 8s Gen4,8.0,256.0,media
1,samsung,Samsung Galaxy S25 Ultra,110000,True,qualcomm,Snapdragon 8 Elite for Galaxy,12.0,256.0,alta
2,vivo,Vivo T5 Pro,29999,True,qualcomm,Snapdragon 7s Gen4,8.0,128.0,media
3,samsung,Samsung Galaxy S25 FE,50743,True,samsung,Exynos 2400,8.0,128.0,media
4,vivo,Vivo T5x 5G,18999,True,mediatek,Dimensity 7400 Turbo,6.0,128.0,media
...,...,...,...,...,...,...,...,...,...
992,realme,Realme C85 5G (6GB RAM + 128GB),17999,True,mediatek,Dimensity 6300,6.0,128.0,media
993,vivo,Vivo X500,57990,True,mediatek,Dimensity 9600,12.0,256.0,alta
994,vivo,Vivo Y19s 5G (4GB RAM + 128GB),13499,True,mediatek,Dimensity 6300,4.0,128.0,baixa
995,oukitel,Oukitel WP60 5G,24699,True,mediatek,Dimensity 7025,8.0,256.0,media
996,vivo,Vivo S50,39990,True,qualcomm,Snapdragon 8s Gen3,12.0,256.0,alta

In [203]:
# exporta o dataframe celulares
celulares.to_csv('celulares_pratica.csv')